### ISSUE TITLE
Searching for " causes an error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [alumae/tsab#10]
```
What steps will reproduce the problem?
1. Open http://bark.phon.ioc.ee/tsab/p/index
2. Type " in to the Otsi-field
3. Press "Otsi"

What is the expected output? What do you see instead?

Expected something other than an error condition. Instead the server returns 
500 with the message:

Cannot parse '"*': Lexical error at line 1, column 3.  Encountered: <EOF> after 
: "\"*"





```

Original issue reported on code.google.com by `kaljurand` on 24 Mar 2015 at 11:43

Attachments:
* [tsab_searching_for_quote.png](https://storage.googleapis.com/google-code-attachments/tsab/issue-10/comment-0/tsab_searching_for_quote.png)

**Comment by alumae** [comment]
Fixed, searching for e.g. "Angela Merkel" now works as expected. Also, full Lucene search syntax is now allowed, including "AND/OR": Searching for "Kaarel AND Tanel" only shows documents that include both Tanel and Kaarel (not necessarily in the same utterance).
